name: 'Setup'
description: 'Sets up the repository'
runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        version: latest
    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
    - name: Generate api typings
      shell: bash
      run: pnpm gen:graphql:prod
